### ISSUE TITLE
Question:  batch id in batch operation 

### ISSUE THREAD

**Issue by DaisyHsiung** [Kinetic/kinetic-py#35]
kinetic.proto mentions that batch id must be unique within the same connection.
In below case, there are two batch objects associated with same batch id within the same connection.
Shouldn't obj2.commit() failed in this case? 

c = Client("127.0.0.1", 8123);
c.connect()
c.put('hi','0')
obj1 = c.begin_batch(batch_id=1)
obj1.put('hi', 'batch_obj1')
obj2 = c.begin_batch(batch_id=1)
obj2.put('hi','batch_obj2')
obj1.commit()
obj2.commit()

**Comment by igomez06** [comment]
The script user does not set the batch_id. This is done by the client, by incrementing each time there is a new batch. If you set c.debug = True, then you will see the proto message reflect as such.
